  server:
    port: 8001

  spring:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
#          show_sql: true
          format_sql: true


    datasource:
#      url: jdbc:mysql://localhost:3306/ssg_point?serverTimezone=Asia/Seoul
#      username: pjm
#      password: jmjm1102
#      driver-class-name: com.mysql.cj.jdbc.Driver
      master:
        hikari:
          jdbc-url: jdbc:mysql://3.35.193.212:3310/ssgdb
          read-only: false
          username: root
          password: 1234
          driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        hikari:
          jdbc-url: jdbc:mysql://3.35.193.212:3311/ssgdb
          read-only: true
          username: root
          password: 1234
          driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      redis:
        host: 3.35.193.212
        port: 6379
      web:
        pageable:
          one-indexed-parameters: true


  logging.level:
    org.hibernate.SQL: debug

  JWT:
    secret_key: fbcb542e08e7feed1c9ebc3740ee092f43304e0b8a666d63bc36fbe785ad447a
    expiration_time: 14400000
    header: Authorization
    prefix: Bearer
    token:
      access-expiration-time: 60000000000  # 원래 14400000 12??
      refresh-expiration-time: 60000   # 1분 7?  180000  604800000

  cloud:
    aws:
      s3:
        bucket: ssgpoint
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: AKIATYFWGSCF3AGZCJXF
        secretKey: 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
  store:
    emart24:
      prefix: 12345678
    emarteveryday:
      prefix: 87654321
    shinsegae:
      prefix: 11223344
    speedmate:
      prefix: 44332211